"""Tests for data models (QuestionItem and Report)"""

import pytest
from datetime import datetime
from pydantic import ValidationError

from app.models.question_item import QuestionItem
from app.models.report import Report, ReportMeta


class TestQuestionItem:
    def test_create_valid_question_item(self):
        """Test creating a valid QuestionItem"""
        item = QuestionItem(
            id=1,
            view_role="技术面试官",
            tag="系统设计",
            question="请设计一个分布式缓存系统",
            rationale="考察候选人对分布式系统的理解",
            baseline_answer="应该考虑数据分片、一致性哈希、缓存失效策略等",
            support_notes="推荐阅读《设计数据密集型应用》",
            prompt_template="请结合你的项目经验，详细描述如何设计一个分布式缓存系统。重点说明：\n{your_experience}"
        )

        assert item.id == 1
        assert item.view_role == "技术面试官"
        assert item.tag == "系统设计"
        assert len(item.question) > 0
        assert len(item.rationale) > 0

    def test_question_item_required_fields(self):
        """Test that required fields are enforced"""
        with pytest.raises(ValidationError):
            QuestionItem()  # Missing all required fields

    def test_question_item_field_types(self):
        """Test field type validation"""
        with pytest.raises(ValidationError):
            QuestionItem(
                id="not_an_int",  # Should be int
                view_role="技术面试官",
                tag="系统设计",
                question="Question",
                rationale="Rationale",
                baseline_answer="Answer",
                support_notes="Notes",
                prompt_template="Template"
            )

    def test_question_item_string_validation(self):
        """Test string length validation"""
        with pytest.raises(ValidationError):
            QuestionItem(
                id=1,
                view_role="A",  # Too short
                tag="B",
                question="C",  # Too short
                rationale="D",
                baseline_answer="E",
                support_notes="F",
                prompt_template="G"
            )

    def test_question_item_dict_conversion(self):
        """Test converting to dict"""
        item = QuestionItem(
            id=1,
            view_role="技术面试官",
            tag="系统设计",
            question="请描述系统设计问题",
            rationale="提问理由" * 10,
            baseline_answer="基准答案" * 10,
            support_notes="支持材料" * 10,
            prompt_template="练习提示词" * 10
        )

        item_dict = item.model_dump()

        assert isinstance(item_dict, dict)
        assert item_dict['id'] == 1
        assert item_dict['view_role'] == "技术面试官"


class TestReportMeta:
    def test_create_report_meta(self):
        """Test creating ReportMeta"""
        meta = ReportMeta(
            generated_at="2025-11-17T10:00:00Z",
            model="claude-sonnet-4",
            config_version="v1.0",
            num_questions=15
        )

        assert meta.generated_at == "2025-11-17T10:00:00Z"
        assert meta.model == "claude-sonnet-4"
        assert meta.config_version == "v1.0"
        assert meta.num_questions == 15

    def test_report_meta_defaults(self):
        """Test ReportMeta with minimal fields (uses defaults)"""
        meta = ReportMeta(
            num_questions=10
        )

        # Should use default values
        assert meta.generated_at is not None  # Generated by default factory
        assert meta.model == "claude-sonnet-4"  # Default model
        assert meta.config_version == "v1.0"  # Default version
        assert meta.num_questions == 10


class TestReport:
    @pytest.fixture
    def sample_questions(self):
        """Sample questions for testing"""
        return [
            QuestionItem(
                id=i,
                view_role="技术面试官",
                tag="算法" if i % 2 == 0 else "系统设计",
                question=f"测试问题{i}" * 3,
                rationale=f"测试理由{i}" * 5,
                baseline_answer=f"测试答案{i}" * 10,
                support_notes=f"测试材料{i}" * 5,
                prompt_template=f"测试模板{i}" * 10
            )
            for i in range(1, 16)
        ]

    def test_create_valid_report(self, sample_questions):
        """Test creating a valid Report"""
        report = Report(
            summary="这是一份针对后端开发工程师岗位的面试准备报告" * 10,
            mode="job",
            target_desc="字节跳动后端开发工程师",
            highlights="候选人在分布式系统和数据库方面有扎实的经验" * 5,
            risks="需要加强算法和系统设计的理论深度" * 5,
            questions=sample_questions,
            meta=ReportMeta(
                generated_at="2025-11-17T10:00:00Z",
                model="claude-sonnet-4",
                config_version="v1.0",
                num_questions=15
            )
        )

        assert report.mode == "job"
        assert len(report.questions) == 15
        assert report.meta.num_questions == 15
        assert "后端开发" in report.target_desc

    def test_report_required_fields(self):
        """Test that required fields are enforced"""
        with pytest.raises(ValidationError):
            Report()  # Missing all required fields

    def test_report_summary_length_validation(self):
        """Test summary length validation"""
        with pytest.raises(ValidationError):
            Report(
                summary="短",  # Too short (< 100 chars)
                mode="job",
                target_desc="工程师",
                highlights="亮点" * 10,
                risks="风险" * 10,
                questions=[],
                meta=ReportMeta(
                    generated_at="2025-11-17T10:00:00Z",
                    model="claude-sonnet-4",
                    num_questions=0
                )
            )

    def test_report_question_count_validation(self, sample_questions):
        """Test question count validation"""
        # Too few questions
        with pytest.raises(ValidationError):
            Report(
                summary="测试摘要" * 20,
                mode="job",
                target_desc="工程师",
                highlights="亮点" * 10,
                risks="风险" * 10,
                questions=sample_questions[:5],  # Only 5 questions (need 10-20)
                meta=ReportMeta(
                    generated_at="2025-11-17T10:00:00Z",
                    model="claude-sonnet-4",
                    num_questions=5
                )
            )

    def test_report_dict_conversion(self, sample_questions):
        """Test converting Report to dict"""
        report = Report(
            summary="测试摘要" * 20,
            mode="job",
            target_desc="字节跳动后端工程师",
            highlights="测试亮点" * 10,
            risks="测试风险" * 10,
            questions=sample_questions,
            meta=ReportMeta(
                generated_at="2025-11-17T10:00:00Z",
                model="claude-sonnet-4",
                config_version="v1.0",
                num_questions=15
            )
        )

        report_dict = report.model_dump()

        assert isinstance(report_dict, dict)
        assert report_dict['mode'] == 'job'
        assert len(report_dict['questions']) == 15
        assert 'meta' in report_dict
        assert report_dict['meta']['num_questions'] == 15

    def test_report_json_serialization(self, sample_questions):
        """Test JSON serialization"""
        report = Report(
            summary="测试摘要" * 20,
            mode="grad",
            target_desc="计算机视觉研究生",
            highlights="测试亮点" * 10,
            risks="测试风险" * 10,
            questions=sample_questions,
            meta=ReportMeta(
                generated_at="2025-11-17T10:00:00Z",
                model="claude-sonnet-4",
                num_questions=15
            )
        )

        json_str = report.model_dump_json()

        assert isinstance(json_str, str)
        assert '"mode":"grad"' in json_str or '"mode": "grad"' in json_str
        assert "计算机视觉" in json_str

    def test_report_mode_validation(self, sample_questions):
        """Test mode field validation"""
        with pytest.raises(ValidationError):
            Report(
                summary="测试摘要" * 20,
                mode="invalid_mode",  # Not job/grad/mixed
                target_desc="工程师",
                highlights="亮点" * 10,
                risks="风险" * 10,
                questions=sample_questions,
                meta=ReportMeta(
                    generated_at="2025-11-17T10:00:00Z",
                    model="claude-sonnet-4",
                    num_questions=15
                )
            )

    def test_report_with_max_questions(self):
        """Test report with maximum questions (20)"""
        questions = [
            QuestionItem(
                id=i,
                view_role="技术面试官",
                tag="算法",
                question=f"问题{i}" * 3,
                rationale=f"理由{i}" * 5,
                baseline_answer=f"答案{i}" * 10,
                support_notes=f"材料{i}" * 5,
                prompt_template=f"模板{i}" * 10
            )
            for i in range(1, 21)
        ]

        report = Report(
            summary="测试摘要" * 20,
            mode="mixed",
            target_desc="全栈工程师",
            highlights="亮点" * 10,
            risks="风险" * 10,
            questions=questions,
            meta=ReportMeta(
                generated_at="2025-11-17T10:00:00Z",
                model="claude-sonnet-4",
                num_questions=20
            )
        )

        assert len(report.questions) == 20
        assert report.meta.num_questions == 20
